#
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def Fabonachi(limit):
    sum = 0
    previousNumber = 1
    number = 2
    nums = [1]
    while(number < limit):
        nums.append(number)
        x = number
        number = previousNumber + number
        previousNumber = x
    for num in nums:
        if num%2 ==0:
            sum += num

    return sum
print(Fabonachi(4000000))
